md _classicsvert
move asteroid.zip _classicsvert
move bwidow.zip _classicsvert
move centiped.zip _classicsvert
move circusc.zip _classicsvert
move digdug.zip _classicsvert
move digdug2.zip _classicsvert
move dkong.zip _classicsvert
move dkong3.zip _classicsvert
move dkongjr.zip _classicsvert
move docastle.zip _classicsvert
move frogger.zip _classicsvert
move galaga.zip _classicsvert
move galaxian.zip _classicsvert
move gorf.zip _classicsvert
move gyruss.zip _classicsvert
move invaders.zip _classicsvert
move jjack.zip _classicsvert
move jrpacman.zip _classicsvert
move ladybug.zip _classicsvert
move mappy.zip _classicsvert
move minefld.zip _classicsvert
move minivadr.zip _classicsvert
move mrdo.zip _classicsvert
move mspacman.zip _classicsvert
move ozmawars.zip _classicsvert
move pacman.zip _classicsvert
move pisces.zip _classicsvert
move pooyan.zip _classicsvert
move puckman.zip _classicsvert
move punchout.zip _classicsvert
move radarscp.zip _classicsvert
move rocnrope.zip _classicsvert
move scobra.zip _classicsvert
move scramble.zip _classicsvert
move sdungeon.zip _classicsvert
move spiders.zip _classicsvert
move tempest.zip _classicsvert
move zaxxon.zip _classicsvert
