md _horshmups
move airbustr.zip _horshmups
move blazeon.zip _horshmups
move blkheart.zip _horshmups
move boogwing.zip _horshmups
move cavenger.zip _horshmups
move choplift.zip _horshmups
move cosmccop.zip _horshmups
move cotton.zip _horshmups
move cotton2.zip _horshmups
move darius.zip _horshmups
move darius2.zip _horshmups
move dariusg.zip _horshmups
move dbreed.zip _horshmups
move deathsml.zip _horshmups
move dsmbl.zip _horshmups
move edf.zip _horshmups
move fantjour.zip _horshmups
move fantzn2x.zip _horshmups
move fantzone.zip _horshmups
move gforce2.zip _horshmups
move gradius.zip _horshmups
move gradius2.zip _horshmups
move gradius3.zip _horshmups
move gratia.zip _horshmups
move hachamf.zip _horshmups
move hvyunit.zip _horshmups
move hyprduel.zip _horshmups
move inthunt.zip _horshmups
move ironclad.zip _horshmups
move macross2.zip _horshmups
move megablst.zip _horshmups
move mustang.zip _horshmups
move mysticri.zip _horshmups
move nemesis.zip _horshmups
move ordyne.zip _horshmups
move p47.zip _horshmups
move p47aces.zip _horshmups
move parodius.zip _horshmups
move prehisle.zip _horshmups
move rsgun.zip _horshmups
move rtype.zip _horshmups
move rtype2.zip _horshmups
move rtypeleo.zip _horshmups
move salamand.zip _horshmups
move salmndr2.zip _horshmups
move sectionz.zip _horshmups
move sexyparo.zip _horshmups
move sidearms.zip _horshmups
move sokyugrt.zip _horshmups
move soldivid.zip _horshmups
move sonson.zip _horshmups
move strahl.zip _horshmups
move tbyahhoo.zip _horshmups
move tengai.zip _horshmups
move terraf.zip _horshmups
move thndrx2.zip _horshmups
move thunderx.zip _horshmups
move vulcan.zip _horshmups
move xexex.zip _horshmups
move xmultipl.zip _horshmups
move zerowing.zip _horshmups
