md _platform
move athena.zip _platform
move bigkarnk.zip _platform
move blktiger.zip _platform
move bnzabros.zip _platform
move bombjack.zip _platform
move bonkadv.zip _platform
move bubblem.zip _platform
move bublbob2.zip _platform
move bublbobl.zip _platform
move cclimber.zip _platform
move ckongpt2.zip _platform
move cninja.zip _platform
move donghaer.zip _platform
move dynagear.zip _platform
move flicky.zip _platform
move gng.zip _platform
move hcastle.zip _platform
move hharry.zip _platform
move indytemp.zip _platform
move jjsquawk.zip _platform
move joemacr.zip _platform
move jumpcoas.zip _platform
move karnov.zip _platform
move kicker.zip _platform
move liquidk.zip _platform
move mario.zip _platform
move marvland.zip _platform
move mcatadv.zip _platform
move mmonkey.zip _platform
move mrgoemon.zip _platform
move mystwarr.zip _platform
move nspirit.zip _platform
move osman.zip _platform
move pacland.zip _platform
move pipibibs.zip _platform
move psychic5.zip _platform
move rastan.zip _platform
move rbisland.zip _platform
move recalh.zip _platform
move shadowld.zip _platform
move shdancer.zip _platform
move shinobi.zip _platform
move snowbro2.zip _platform
move snowbros.zip _platform
move sonic.zip _platform
move spelunk2.zip _platform
move spelunkr.zip _platform
move suprmrio.zip _platform
move suprtrio.zip _platform
move thoop.zip _platform
move tigeroad.zip _platform
move toki.zip _platform
move trojan.zip _platform
move tumblep.zip _platform
move wardner.zip _platform
move wb3.zip _platform
move wbml.zip _platform
move wboy.zip _platform
