md _ports
move mp_bio.zip _ports
move mp_gaxe2.zip _ports
move mp_gslam.zip _ports
move mp_shnb3.zip _ports
move mp_soni2.zip _ports
move mp_sonic.zip _ports
move mp_sor2.zip _ports
move mt_bbros.zip _ports
move mt_revsh.zip _ports
move mt_shnbi.zip _ports
move mt_soni2.zip _ports
move mt_sonic.zip _ports
move mt_spman.zip _ports
move mt_srage.zip _ports
move nss_actr.zip _ports
move nss_adam.zip _ports
move nss_con3.zip _ports
move nss_lwep.zip _ports
move nss_rob3.zip _ports
move nss_skin.zip _ports
move nss_smw.zip _ports
move pc_bstar.zip _ports
move pc_cntra.zip _ports
move pc_cshwk.zip _ports
move pc_cvnia.zip _ports
move pc_dbldr.zip _ports
move pc_ddrgn.zip _ports
move pc_ebike.zip _ports
move pc_gntlt.zip _ports
move pc_goons.zip _ports
move pc_grdus.zip _ports
move pc_kngfu.zip _ports
move pc_miket.zip _ports
move pc_mman3.zip _ports
move pc_ngai2.zip _ports
move pc_ngai3.zip _ports
move pc_ngaid.zip _ports
move pc_pinbt.zip _ports
move pc_pwbld.zip _ports
move pc_pwrst.zip _ports
move pc_radr2.zip _ports
move pc_radrc.zip _ports
move pc_rcpam.zip _ports
move pc_rkats.zip _ports
move pc_rnatk.zip _ports
move pc_rrngr.zip _ports
move pc_rygar.zip _ports
move pc_sjetm.zip _ports
move pc_smb.zip _ports
move pc_smb2.zip _ports
move pc_smb3.zip _ports
move pc_suprc.zip _ports
move pc_tbowl.zip _ports
move pc_tenis.zip _ports
move pc_tkfld.zip _ports
move pc_tmnt2.zip _ports
move pc_trjan.zip _ports
move pc_wcup.zip _ports
move pss61.zip _ports
move pss63.zip _ports
move suprmrio.zip _ports
