md _puzzle
move 25pacman.zip _puzzle
move amidar.zip _puzzle
move arkanoid.zip _puzzle
move arkretrn.zip _puzzle
move atetris.zip _puzzle
move bbmanw.zip _puzzle
move bbonk.zip _puzzle
move block.zip _puzzle
move blockout.zip _puzzle
move bloxeed.zip _puzzle
move bmfinal.zip _puzzle
move bmiidx7.zip _puzzle
move chainrec.zip _puzzle
move checkman.zip _puzzle
move ddrextrm.zip _puzzle
move ddrmax.zip _puzzle
move ddrmax2.zip _puzzle
move deroon.zip _puzzle
move dmx2m.zip _puzzle
move drmn.zip _puzzle
move drmn10m.zip _puzzle
move exvania.zip _puzzle
move higemaru.zip _puzzle
move hyperpac.zip _puzzle
move jumppop.zip _puzzle
move jungler.zip _puzzle
move lazercmd.zip _puzzle
move levers.zip _puzzle
move mamboagg.zip _puzzle
move marble.zip _puzzle
move maruchan.zip _puzzle
move mushitam.zip _puzzle
move mustache.zip _puzzle
move pacmania.zip _puzzle
move pacplus.zip _puzzle
move pang.zip _puzzle
move pbaction.zip _puzzle
move pbobble2.zip _puzzle
move pbobble2x.zip _puzzle
move pbobble3.zip _puzzle
move pbobble4.zip _puzzle
move puchicar.zip _puzzle
move puzzloop.zip _puzzle
move qix.zip _puzzle
move roadrunn.zip _puzzle
move sbrkout.zip _puzzle
move snowbro3.zip _puzzle
move spaceskr.zip _puzzle
move sqix.zip _puzzle
move supbtime.zip _puzzle
move superpac.zip _puzzle
move tetris.zip _puzzle
move tetrisp.zip _puzzle
move tetrisp2.zip _puzzle
move tgm2.zip _puzzle
move tgm2p.zip _puzzle
move todruaga.zip _puzzle
move volfied.zip _puzzle
