md _runNgun
move actfancr.zip _runNgun
move aliens.zip _runNgun
move aliensyn.zip _runNgun
move avspirit.zip _runNgun
move battlera.zip _runNgun
move biomtoy.zip _runNgun
move bionicc.zip _runNgun
move bucky.zip _runNgun
move bullet.zip _runNgun
move charlien.zip _runNgun
move commando.zip _runNgun
move contra.zip _runNgun
move crazywar.zip _runNgun
move crimec.zip _runNgun
move desertbr.zip _runNgun
move dmnfrnt.zip _runNgun
move elvactr.zip _runNgun
move fixeight.zip _runNgun
move gberet.zip _runNgun
move gijoe.zip _runNgun
move gundhara.zip _runNgun
move gunforc2.zip _runNgun
move gunforce.zip _runNgun
move gunmast.zip _runNgun
move gunsmoke.zip _runNgun
move gwar.zip _runNgun
move ikari.zip _runNgun
move ikari3.zip _runNgun
move ironhors.zip _runNgun
move loht.zip _runNgun
move midres.zip _runNgun
move moomesa.zip _runNgun
move narc.zip _runNgun
move naughtyb.zip _runNgun
move outzone.zip _runNgun
move prikura.zip _runNgun
move rambo3.zip _runNgun
move robocop.zip _runNgun
move robocop2.zip _runNgun
move scontra.zip _runNgun
move sdgndmps.zip _runNgun
move searchar.zip _runNgun
move shootout.zip _runNgun
move smashtv.zip _runNgun
move srumbler.zip _runNgun
move ssriders.zip _runNgun
move swatpolc.zip _runNgun
move thundfox.zip _runNgun
move tinstar.zip _runNgun
move totcarn.zip _runNgun
move valkyrie.zip _runNgun
move victroad.zip _runNgun
