md _shooter
move aburner2.zip _shooter
move airrace.zip _shooter
move alien3.zip _shooter
move apache3.zip _shooter
move aquajack.zip _shooter
move bbusters.zip _shooter
move bloodbro.zip _shooter
move bshark.zip _shooter
move cabal.zip _shooter
move carnevil.zip _shooter
move carnking.zip _shooter
move cryptklr.zip _shooter
move cybertnk.zip _shooter
move duckhunt.zip _shooter
move evilngt.zip _shooter
move funkyfig.zip _shooter
move irobot.zip _shooter
move jpark.zip _shooter
move le2.zip _shooter
move lethalen.zip _shooter
move lghost.zip _shooter
move loffire.zip _shooter
move luckywld.zip _shooter
move mechatt.zip _shooter
move nightstr.zip _shooter
move opwolf.zip _shooter
move opwolf3.zip _shooter
move othunder.zip _shooter
move ptblank.zip _shooter
move ptblank2.zip _shooter
move ptblank3.zip _shooter
move rchase.zip _shooter
move revx.zip _shooter
move senjyo.zip _shooter
move sgunner.zip _shooter
move sgunner2.zip _shooter
move sonicfgt.zip _shooter
move skydest.zip _shooter
move stunrun.zip _shooter
move term2.zip _shooter
move topgun.zip _shooter
move totlvice.zip _shooter
move undrfire.zip _shooter
move zeropnt.zip _shooter
move zeropnt2.zip _shooter
move zombraid.zip _shooter
