md _sports
move 3on3dunk.zip _sports
move 88games.zip _sports
move archrivl.zip _sports
move bcstry.zip _sports
move bladestl.zip _sports
move bssoccer.zip _sports
move cbasebal.zip _sports
move darkhleg.zip _sports
move ddribble.zip _sports
move decathlt.zip _sports
move evosocc.zip _sports
move excitebk.zip _sports
move goldmedl.zip _sports
move gridiron.zip _sports
move gtmr.zip _sports
move harddunk.zip _sports
move hoops96.zip _sports
move hvysmsh.zip _sports
move jockeyc.zip _sports
move machbrkr.zip _sports
move madgear.zip _sports
move majtitl2.zip _sports
move majtitle.zip _sports
move nbagold.zip _sports
move nbahangt.zip _sports
move nbajam.zip _sports
move nbajamte.zip _sports
move numanath.zip _sports
move openice.zip _sports
move pblbeach.zip _sports
move pigskin.zip _sports
move pingpong.zip _sports
move powerbal.zip _sports
move pspikes.zip _sports
move punkshot.zip _sports
move pwrgoal.zip _sports
move rbibb.zip _sports
move relief.zip _sports
move rollerg.zip _sports
move rungun.zip _sports
move rungun2.zip _sports
move rushhero.zip _sports
move sasissu.zip _sports
move scfinals.zip _sports
move slapshot.zip _sports
move soccerss.zip _sports
move spdodgeb.zip _sports
move sslam.zip _sports
move stonebal.zip _sports
move suprleag.zip _sports
move suprslam.zip _sports
move swcourt.zip _sports
move sws.zip _sports
move sws95.zip _sports
move sws96.zip _sports
move sws97.zip _sports
move tbowl.zip _sports
move topbladv.zip _sports
move trackfld.zip _sports
move ultennis.zip _sports
move usclssic.zip _sports
move vball.zip _sports
move vbowl.zip _sports
move vsbball.zip _sports
move vsnetscr.zip _sports
move wbbc97.zip _sports
move wbeachvl.zip _sports
move wcbowldx.zip _sports
move wcvol95.zip _sports
move wldcourt.zip _sports
move wlstar.zip _sports
move wondl96.zip _sports
move wwfmania.zip _sports
move wwfwfest.zip _sports
