md _vertshmups
move 1942.zip _vertshmups
move 1943.zip _vertshmups
move 1943kai.zip _vertshmups
move 1945kiii.zip _vertshmups
move acrobatm.zip _vertshmups
move aerofgt.zip _vertshmups
move agallet.zip _vertshmups
move airass.zip _vertshmups
move airduel.zip _vertshmups
move ajax.zip _vertshmups
move alphamis.zip _vertshmups
move arbalest.zip _vertshmups
move aso.zip _vertshmups
move batrider.zip _vertshmups
move batsugun.zip _vertshmups
move batsugunsp.zip _vertshmups
move bbakraid.zip _vertshmups
move bermudat.zip _vertshmups
move bgaregga.zip _vertshmups
move blswhstl.zip _vertshmups
move bluehawk.zip _vertshmups
move cairblad.zip _vertshmups
move chopper.zip _vertshmups
move cybattlr.zip _vertshmups
move cyvern.zip _vertshmups
move ddonpach.zip _vertshmups
move ddp2.zip _vertshmups
move ddpdfk.zip _vertshmups
move ddpdoj.zip _vertshmups
move dogyuun.zip _vertshmups
move donpachi.zip _vertshmups
move dragnblz.zip _vertshmups
move dsaber.zip _vertshmups
move dspirit.zip _vertshmups
move earthjkr.zip _vertshmups
move eightfrc.zip _vertshmups
move espgal.zip _vertshmups
move espgal2.zip _vertshmups
move esprade.zip _vertshmups
move exedexes.zip _vertshmups
move explbrkr.zip _vertshmups
move extrmatn.zip _vertshmups
move feversos.zip _vertshmups
move fghtatck.zip _vertshmups
move firebarr.zip _vertshmups
move firehawk.zip _vertshmups
move fshark.zip _vertshmups
move fstarfrc.zip _vertshmups
move futari15.zip _vertshmups
move futaribl.zip _vertshmups
move gaialast.zip _vertshmups
move galaga88.zip _vertshmups
move gametngk.zip _vertshmups
move gekiridn.zip _vertshmups
move grdnstrm.zip _vertshmups
move grindstm.zip _vertshmups
move gseeker.zip _vertshmups
move gstream.zip _vertshmups
move gulfwar2.zip _vertshmups
move gunbird.zip _vertshmups
move gunbird2.zip _vertshmups
move gunlock.zip _vertshmups
move gunnail.zip _vertshmups
move guwange.zip _vertshmups
move hotdogst.zip _vertshmups
move ibara.zip _vertshmups
move ibarablk.zip _vertshmups
move jackal.zip _vertshmups
move ket.zip _vertshmups
move kingdmgp.zip _vertshmups
move lastduel.zip _vertshmups
move lethalth.zip _vertshmups
move lgtnfght.zip _vertshmups
move lwings.zip _vertshmups
move macross.zip _vertshmups
move macrossp.zip _vertshmups
move madshark.zip _vertshmups
move mazinger.zip _vertshmups
move megazone.zip _vertshmups
move metlhawk.zip _vertshmups
move misncrft.zip _vertshmups
move mmpork.zip _vertshmups
move mushisam.zip _vertshmups
move nebulray.zip _vertshmups
move nost.zip _vertshmups
move phelios.zip _vertshmups
move pinkswts.zip _vertshmups
move raiden.zip _vertshmups
move raiden2.zip _vertshmups
move raidendx.zip _vertshmups
move rdft.zip _vertshmups
move rdft2.zip _vertshmups
move rfjet.zip _vertshmups
move rshark.zip _vertshmups
move s1945.zip _vertshmups
move s1945ii.zip _vertshmups
move s1945iii.zip _vertshmups
move samuraia.zip _vertshmups
move sandscrp.zip _vertshmups
move sbomber.zip _vertshmups
move sengekis.zip _vertshmups
move shienryu.zip _vertshmups
move silvmil.zip _vertshmups
move skullfng.zip _vertshmups
move skyalert.zip _vertshmups
move spec2k.zip _vertshmups
move ssmissin.zip _vertshmups
move sstriker.zip _vertshmups
move stagger1.zip _vertshmups
move stmblade.zip _vertshmups
move superx.zip _vertshmups
move tcobra2.zip _vertshmups
move tdragon.zip _vertshmups
move tdragon2.zip _vertshmups
move tharrier.zip _vertshmups
move thndrbld.zip _vertshmups
move tigerh.zip _vertshmups
move timeplt.zip _vertshmups
move truxton.zip _vertshmups
move truxton2.zip _vertshmups
move twinbee.zip _vertshmups
move twincobr.zip _vertshmups
move twineag2.zip _vertshmups
move twineagl.zip _vertshmups
move twinhawk.zip _vertshmups
move ultrax.zip _vertshmups
move vaportra.zip _vertshmups
move vasara.zip _vertshmups
move vasara2.zip _vertshmups
move viprp1.zip _vertshmups
move vmetal.zip _vertshmups
move vulgus.zip _vertshmups
move wivernwg.zip _vertshmups
move wrofaero.zip _vertshmups
move wyvernwg.zip _vertshmups
move xevious.zip _vertshmups
move x2222.zip _vertshmups
move xplan.zip _vertshmups
move zingzip.zip _vertshmups
