md _zBIOS
move 22vp931.zip _zBIOS
move aleck64.zip _zBIOS
move alg_bios.zip _zBIOS
move allied.zip _zBIOS
move ar_bios.zip _zBIOS
move aristmk5.zip _zBIOS
move aristmk6.zip _zBIOS
move atarisy1.zip _zBIOS
move bsmt2000.zip _zBIOS
move bubsys.zip _zBIOS
move cchip.zip _zBIOS
move crysbios.zip _zBIOS
move cubo.zip _zBIOS
move decocass.zip _zBIOS
move galgbios.zip _zBIOS
move gp_110.zip _zBIOS
move gq863.zip _zBIOS
move gts1.zip _zBIOS
move gts1s.zip _zBIOS
move hd44780_a00.zip _zBIOS
move isgsm.zip _zBIOS
move iteagle.zip _zBIOS
move k573_dio.zip _zBIOS
move k573msu.zip _zBIOS
move konamigv.zip _zBIOS
move konamigx.zip _zBIOS
move ldv1000.zip _zBIOS
move m1comm.zip _zBIOS
move m50458.zip _zBIOS
move m68705p3.zip _zBIOS
move m68705p5.zip _zBIOS
move m68705r3.zip _zBIOS
move m68705u3.zip _zBIOS
move macsbios.zip _zBIOS
move maxaflex.zip _zBIOS
move megaplay.zip _zBIOS
move megatech.zip _zBIOS
move midssio.zip _zBIOS
move model1io.zip _zBIOS
move model1io2.zip _zBIOS
move namco50.zip _zBIOS
move namco51.zip _zBIOS
move namco52.zip _zBIOS
move namco53.zip _zBIOS
move namco54.zip _zBIOS
move namco62.zip _zBIOS
move namcoc65.zip _zBIOS
move namcoc68.zip _zBIOS
move namcoc69.zip _zBIOS
move namcoc70.zip _zBIOS
move namcoc75.zip _zBIOS
move nmk004.zip _zBIOS
move nss.zip _zBIOS
move pgm.zip _zBIOS
move playch10.zip _zBIOS
move pr8210.zip _zBIOS
move pyson.zip _zBIOS
move saa5050.zip _zBIOS
move segabill.zip _zBIOS
move sfcbox.zip _zBIOS
move shtzone.zip _zBIOS
move simutrek.zip _zBIOS
move skns.zip _zBIOS
move stvbios.zip _zBIOS
move su2000.zip _zBIOS
move sys246.zip _zBIOS
move sys256.zip _zBIOS
move sys573.zip _zBIOS
move taitotz.zip _zBIOS
move tms32031.zip _zBIOS
move tms32032.zip _zBIOS
move tourvis.zip _zBIOS
move v4bios.zip _zBIOS
move votrax.zip _zBIOS
